name = "fpjs-metrics-beta"
type = "javascript"
account_id = ""
zone_id = ""
route = ""


[vars]
api_base_route = "/abcd1234"
script_download_subpath = "/ghjklmno56789"
get_endpoint_subpath = "/qwerty13579"

[build]
command = "npm install && npm run build"

[build.upload]
format = "service-worker"
